import requests
import config
import re
import string
import urllib.parse

from lxml import etree, html
from time import sleep
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait

def captchaReader(htmlContent):
    return html.fromstring(htmlContent).xpath('string(//*[@data-sitekey]/@data-sitekey)')

def captchaResult(args, headers):
    task = re.search('OK\|(?P<id>.+)', args)
    if task is None:
        raise Exception(args)
    url = 'http://2captcha.com/res.php'
    querystring = {"key":config.apiKey,"action":"get","id":task['id']}
    while True:
        sleep(5)
        result = requests.request("POST", url, headers=headers, params=querystring).text
        if result == 'ERROR_CAPTCHA_UNSOLVABLE':
            raise Exception(result)
        if result != 'CAPCHA_NOT_READY':
            return result[3::]

def solveCaptcha(siteKey, siteUrl):
    url = 'https://2captcha.com/in.php'
    host = '2captcha.com'

    querystring = {"key":config.apiKey,"method":"userrecaptcha","googlekey":siteKey,"pageurl":siteUrl}

    headers = {
        'Accept': "*/*",
        'Cache-Control': "no-cache",
        'Host': host,
        'Accept-Encoding': "gzip, deflate",
        'Content-Length': "0",
        'Connection': "keep-alive",
        'cache-control': "no-cache"
        }

    args = requests.request("POST", url, headers=headers, params=querystring).text

    return captchaResult(args, headers)

def getCaptchaResponse(htmlContent, siteUrl):
    challenge = captchaReader(htmlContent)
    hashResult = solveCaptcha(challenge, siteUrl)
    return hashResult

def clickAction(url, headers, querystring, hashResult):
    driver = webdriver.Chrome()
    #storing the cookies generated by the browser
    request_cookies_browser = driver.get_cookies()
    urlAction = "{}?{}".format(url, urllib.parse.urlencode(querystring))
    driver.get(urlAction)
    driver.execute_script('var element=document.getElementById("g-recaptcha-response"); element.style.display="";')
    driver.execute_script('document.getElementById("g-recaptcha-response").innerHTML="{}"'.format(hashResult))
    driver.execute_script('document.getElementById("formConsulta").submit()')
    return driver.page_source